== Steps to generate a blog using this engine

Create a new rails app:

  rails new badass-demo

Edit the gemfile and add the badass gem:

  gem 'badass', :git => 'git@github.com:mpatric/badass.git', :branch => 'master'
  
Make sure you have bundler installed:

  gem install bundler
  
  (or sudo gem install bundler if you're not using rvm)

Run bundler:

  bundle

Run the badass generator:

  rails g badass:site -f

Update database.yml as appropriate, then create your database and run the migrations:

  rake db:create
  rake db:migrate

If you wish to generate some test data, run:

  rake db:seed

Start rails locally:

  rails s

Go to http://localhost:3000/admin with your web browser for the admin interface, if you've generated test data login with test/test

Go to http://localhost:3000/ with your web browser for the blog


== Customising the app:

Edit the configuration file config/badass.yml. The keys are fairly self-explanatory. If you want to use akismet for spam protection you will need to register at http://akismet.com/ and get an API key. If you want to track analytics with google analytics you will need your analytics account id (the number starting 'UA-').

Edit the Amazon s3 configuration in config/s3.yml to include your access key id and secret access key. You will need to sign up for Amazon web services to use this. You won't be able to upload assets to your blog without setting up s3 support.

You should probably add password_confirmation to the list of filtered parameters in config/application.rb:

  config.filter_parameters += [:password, :password_confirmation]

If you want some information to appear on the top-right of the page (typically information about yourself), edit the partial /app/views/home/_about.html.erb

If you are setting up a personal blog, you'll probably want to leave max_users for production in badass.yml on 1, which means as soon as you register yourself it won't be possible for other people to register on your site. If you're setting up a blog for multiple people to use, you might want to increase this number.

== Deploying to Heroku:

TODO


== Updating your app to the latest version of badass

It is strongly recommended that the generator is re-run whenever the badass gem is updated, as files generated with the site generator may have changed too. Run:

  rails g badass:site -s
  
That will re-run the site generator, but skip the files you have modified so they don't get over-written. If any new migrations are generated by this you will need to run the migrations:

  rake db:migrate

